name: Generate contents

on:
    # 03:00 (JST) = 18:00 (UTC)
    schedule:
        - cron: "0 18 * * *"

    workflow_dispatch:

    push:
        branches:
            - master

jobs:
    generate:
        name: generate snake🐍
        permissions:
            contents: write

        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout output branch
              uses: actions/checkout@v6
              with:
                  ref: output
                  fetch-depth: 0

            - name: Generate github-contribution-grid-snake.svg
              uses: Platane/snk/svg-only@v3
              with:
                  github_user_name: ${{ github.repository_owner }}
                  outputs: |
                      github-contribution-grid-snake.svg
                      github-contribution-grid-snake-dark.svg?palette=github-dark

            - name: Commit and push
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git add .

                  if git diff --cached --quiet; then
                      echo "No changes to commit."
                      exit 0
                  fi

                  git commit -m "🐍 | update contribution snake"
                  git push origin output
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
